config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'lists#index'
  resources :lists do
    collection do
      get :top
    end
    member do
      get :bookmarks
      get :movies
    end
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: [:list_id]
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  has_many :bookmarks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
      # we need `restaurant_id` to associate review with corresponding restaurant
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    if @bookmark.update(bookmark_params) #this will already save your nested project along with the bookmark
      redirect_to list_path
    else
      render :edit
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end


  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new
    end
  end

  def show
    @list = List.find(params[:id])
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :bookmark, :movies)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <div class="wrap">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      <div class="push"></div>
    </div>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/lists/_form.html.erb
<h1>test</h1>
<%= simple_form_for list do |f| %>
  <%= f.input :name %>
  <%= f.input :bookmarks %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/lists/index.html.erb
<div class="banner" id="banner-cropped">
  <div class="banner-content">
    <h1>Bookmark and list</h1>
    <h1>your favorite movies</h1>
    <button class="button button--pan">
      <span>Make a list</span>
    </button>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="d-flex justify-content-around p-3 text-center">
      <div class="col-xs-12 col-sm-4">
      <% @lists.each do |list| %>
        <div class="card">
          <img src="http://placehold.it/50x50" alt="">
          <div>
            <h1><%= list.name.upcase %></h1>
            <p> movies: <%= list.movies.length %></p>
            <button class="btn btn-dark"><%= link_to "Open list", list_path(list)%></button>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<h1>test</h1>

app/views/lists/show.html.erb
<div>
    <div class="container p-3">
      <h1><%= @list.name %></h1>
    </div>
  <div class="container">
    <div class="row">
      <ul class="list-group col-6">
        <% @list.bookmarks.each do |bookmark| %>
          <div>
            <li class="list-group-item d-flex">
            <div>
              <img class="mx-auto d-block img-fluid img-thumbnail" style="max-width:80%" alt="Responsive image" src=<%= bookmark.movie.poster_url  %>>
            </div>
              <div class="col-6">
                <h3 class="border-bottom"><%= bookmark.movie.title %></h3>
                <p>Comment:<br><%= bookmark.comment %></p>
              </div>
            </li>
            <li class="list-group-item">
                <%= link_to "Remove",
                            bookmark_path(bookmark), class: "btn border",
                            method: :delete,
                            data: { confirm: "Are you sure?" } %>
            </li>
          </div>
        <% end %>
      </ul>
      <div class="col-3">
        <%= link_to "Add movies!", new_list_bookmark_path(@list), class: "btn btn-flat"%>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer fixed-bottom">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <p> Made with love during Le Wagon bootcamp by Edward Toonela </p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/Edwardtoonela/rails-watch-list/master/app/assets/images/popcorn.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>